export const PRIMARY_COLOR = '#6200EE'; // '#3F51B5';

export const PATHVIEW_HEIGHT = 56;
export const TOOLBAR_HEIGHT = 48;
export const TOOLBAR_BUTTON_WIDTH = 36;
export const APPBAR_HEIGHT = PATHVIEW_HEIGHT + TOOLBAR_HEIGHT;
export const DEFAULT_NAV_DRAWER_WIDTH = 256;
