export const PRIMARY_COLOR = '#3F51B5';

export const PATHVIEW_HEIGHT = 48;
export const TOOLBAR_HEIGHT = 48;
export const TOOLBAR_BUTTON_WIDTH = 48;
export const APPBAR_HEIGHT = PATHVIEW_HEIGHT + TOOLBAR_HEIGHT;
export const NAVIGATION_DRAWER_PERSISTENT_WIDTH = 64;
