export const icons = {
  add: require('~/renderer/resources/icons/add.svg'),
  close: require('~/renderer/resources/icons/close.svg'),
  chevronRight: require('~/renderer/resources/icons/chevron-right.svg'),
  refresh: require('~/renderer/resources/icons/refresh.svg'),
  folder: require('~/renderer/resources/icons/folder.svg'),
  file: require('~/renderer/resources/icons/file.svg'),
  back: require('~/renderer/resources/icons/back.svg'),
  forward: require('~/renderer/resources/icons/forward.svg'),
  star: require('~/renderer/resources/icons/star.svg'),
  dropDown: require('~/renderer/resources/icons/drop-down.svg'),
  fileOutline: require('~/renderer/resources/icons/file-outline.svg'),
  search: require('~/renderer/resources/icons/search.svg'),
  fileTree: require('~/renderer/resources/icons/file-tree.svg'),
  visible: require('~/renderer/resources/icons/visible.svg'),
  invisible: require('~/renderer/resources/icons/invisible.svg'),
  sitesManager: require('~/renderer/resources/icons/sites-manager.svg'),
  download: require('~/renderer/resources/icons/download.svg'),
  transfer: require('~/renderer/resources/icons/transfer.svg'),
}
